services:
  - type: web
    name: ml-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --workers=1 --timeout 90
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
